<script defer type="module" src="{{ url("/build/assets/Add.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/dialog.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Drop.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Drop2.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Edit.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Forget.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Home.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/index.esm.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/index.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/index2.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Login.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Logo.js") }}"></script>
<link rel="stylesheet" href="{{ url("/build/assets/main.css") }}"/>
<script defer type="module" src="{{ url("/build/assets/main.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Pagination.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/ProtectedLayout.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/PublicLayout.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Register.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Reset.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/transition.js") }}"></script>
<script defer type="module" src="{{ url("/build/assets/Verify.js") }}"></script>
